version: '3'
services:
  web:
    build:
      context: '.'
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=boilerplate-database
      - DB_USER=boilerplate-database-username
      - DB_PASSWORD=boilerplate-database-password
      - JWT_SECRET_KEY=Mdc6PVaq-q*sxFnFjvA@LhAs
      - JWT_EXPIRATION_SECONDS=3600
#      - DEBUG=loopback:*
    networks:
      - boilerplate-network
    volumes:
      - .:/home/node/app
#    command: nodemon --delay 2s -e ts,json --ignore './dist' --watch /home/node/app/src --exec "yarn run start"
    command: "yarn run start"
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=boilerplate-database
      - POSTGRES_USER=boilerplate-database-username
      - POSTGRES_PASSWORD=boilerplate-database-password
    networks:
      - boilerplate-network
networks:
  boilerplate-network:
    driver: bridge