version: '3'
services:
  web:
    build:
      context: '.'
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=boilerplate-database
      - DB_USER=boilerplate-database-username
      - DB_PASSWORD=boilerplate-database-password
      - JWT_SECRET_KEY=Mdc6PVaq-q*sxFnFjvA@LhAs
      - JWT_EXPIRATION_SECONDS=3600
#      - DEBUG=loopback:*
    networks:
      - boilerplate-network
    volumes:
      - boilerplate-web-app:/home/node/app
#    command: nodemon --delay 2s -e ts,json --ignore './dist' --watch /home/node/app/src --exec "yarn run start"
    command: "yarn run start"
  postgres:
    image: "postgres:15.1"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=boilerplate-database
      - POSTGRES_USER=boilerplate-database-username
      - POSTGRES_PASSWORD=boilerplate-database-password
    networks:
      - boilerplate-network
    volumes:
      - boilerplate-postgres:/var/lib/postgresql/data
  postgres_test:
    image: "postgres:15.1"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=test-database
      - POSTGRES_USER=test-username
      - POSTGRES_PASSWORD=test-password
    networks:
      - boilerplate-network
    volumes:
      - boilerplate-postgres-test:/var/lib/postgresql/data
networks:
  boilerplate-network:
    driver: bridge
volumes:
  boilerplate-web-app:
  boilerplate-postgres:
  boilerplate-postgres-test: