version: '3'
services:
  web:
    build:
      context: '.'
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE_NAME=boilerplate-database
      - MONGO_USER=boilerplate-database-username
      - MONGO_PASSWORD=boilerplate-database-password
#      - DEBUG=loopback:*
    volumes:
      - .:/home/node/app
#    command: nodemon --delay 2s -e ts,json --ignore './dist' --watch /home/node/app/src --exec "yarn run start"
    command: "yarn run start"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=boilerplate-database
      - MONGO_INITDB_ROOT_USERNAME=boilerplate-database-username
      - MONGO_INITDB_ROOT_PASSWORD=boilerplate-database-password